dist: trusty
language: csharp
install:
  - nvm install 10.16.3
  - nvm use 10.16.3
script:
  - nuget restore $TRAVIS_BUILD_DIR/Integration/WindowsApp/Live.sln
  - msbuild /p:Configuration=Release $TRAVIS_BUILD_DIR/Integration/WindowsApp/Live.sln
  - cd $TRAVIS_BUILD_DIR/Live
  - npm install
  - npm run test
  - npm run build-prod
notifications:
  email:
    on_failure: always
