language: csharp
solution: Service/Service.sln
install:
  - nuget Restore Service/Service.sln
  - nuget Install NUnit.ConsoleRunner -Version 3.9.0 -OutputDirectory Service/TestRunner
script:
  - msbuild /p:Configuration=Release Service/Service.sln
  - Service/TestRunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe Service/LivestreamApp.Api.Test/bin/Release/LivestreamApp.Api.Test.dll
notifications:
  email: false
