dist: trusty
language: node_js
addons:
  sonarcloud:
    organization: "chrisdoernen-github"
    token: $SONAR_TOKEN
install:
  - nvm install 8.11.3
  - nvm use 8.11.3
script:
  - cd $TRAVIS_BUILD_DIR/Live
  - npm install
  - npm run test
  - npm run build-prod
notifications:
  email:
    on_failure: always
