dist: trusty
language: node_js
addons:
  sonarcloud:
    organization: "chrisdoernen-github"
    token: $SONAR_TOKEN
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
install:
  - nvm install 8.11.3
  - nvm use 8.11.3
script:
  - cd Client
  - npm install
  - npm run testCI
  - npm run buildProd
notifications:
  email: false
