name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: application
      run: yarn install

    - name: Test
      working-directory: application
      run: yarn run test

    - name: Build
      working-directory: application
      run: yarn run build-prod

      env:
        CI: true
