name: NIGHTLY BUILD

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: integration

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: application
      run: yarn install

    - name: Test
      working-directory: application
      run: yarn run test

    - name: Build
      working-directory: application
      run: yarn run build-prod

    - name: Download Ffmpeg static files
      working-directory: application
      run: yarn run download-ffmpeg -- --ci

    - name: Install executable dependecies
      working-directory: application/dist/apps/server
      run: yarn install --production

    - name: Create artifacts
      working-directory: application
      run: yarn run create-artifacts

    - name: Collect artifacts
      working-directory: application
      run: yarn run collect-artifacts -- ${{ github.run_number }}-${{ github.run_id }}

    - name: Deploy
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        remoteDir: ${{ secrets.FTP_DIRECTORY }}
        localDir: application/artifacts
        forceSsl: true
